require "fileutils"

default_platform(:ios)

platform :ios do
  desc "Upload Expellio metadata to App Store Connect"
  lane :upload_metadata do
    api_key = app_store_connect_api_key(
      key_id: "TVX56KGPFH",
      issuer_id: "3cb46eb5-0082-43b4-bfb5-f29138dbff5f",
      key_filepath: "./fastlane/AuthKey_TVX56KGPFH.p8",
      in_house: false
    )

    deliver(
      api_key: api_key,
      app_identifier: "com.antonchepur.expellio.app",
      submit_for_review: false,
      skip_screenshots: true,
      skip_binary_upload: true,
      force: true,
      ignore_language_directory_validation: true,
      run_precheck_before_submit: false
    )
  end
end
